# Generated by Django 3.2.13 on 2023-04-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230413_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stars_freelancer',
            field=models.JSONField(null=True),
        ),
    ]
