# Generated by Django 3.2.13 on 2023-04-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230427_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='stars_customer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stars_freelancer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='stars_freelancer',
            field=models.JSONField(null=True),
        ),
    ]
