# Generated by Django 3.2.13 on 2023-04-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_stars_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stars_freelancer',
            field=models.JSONField(default={'star': 0, 'username': None}, null=True),
        ),
    ]
