# Generated by Django 3.2.13 on 2023-09-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_birth_date'),
        ('users', '0008_customuser_birth_date'),
    ]

    operations = [
    ]
