# Generated by Django 3.2.13 on 2023-04-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_stars_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stars_customer',
            field=models.ManyToManyField(blank=True, related_name='stars_customer', to='users.Star', verbose_name='Оценка заказчика'),
        ),
    ]
