# Generated by Django 3.2.13 on 2023-04-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_stars_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stars_freelancer',
            field=models.JSONField(default=[{'star': 0, 'username': None}, {'star': 1, 'username': 1}], null=True),
        ),
    ]
