# Generated by Django 3.2.13 on 2023-11-02 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20230914_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adfile',
            name='ad',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='AdFile',
        ),
    ]
