# Generated by Django 3.2.13 on 2023-11-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20231102_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Star',
        ),
    ]
