# Generated by Django 3.2.13 on 2023-05-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20230504_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stars_customer',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stars_freelancer',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
