# Generated by Django 3.2.13 on 2024-04-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20240404_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, max_length=15, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
