# Generated by Django 3.2.13 on 2024-04-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0005_auto_20240411_1133'),
        ('users', '0015_alter_customuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='stars_customer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stars_freelancer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='stars',
            field=models.ManyToManyField(to='stars.Star', verbose_name='Рейтинг'),
        ),
    ]
