# Generated by Django 3.2.13 on 2024-04-11 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_email'),
        ('users', '0017_alter_customuser_stars'),
    ]

    operations = [
    ]
