# Generated by Django 3.2.13 on 2024-04-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20240411_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='stars',
        ),
        migrations.AddField(
            model_name='customuser',
            name='stars',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
    ]
