# Generated by Django 3.2.13 on 2024-04-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20240418_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
    ]
