# Generated by Django 3.2.13 on 2024-04-18 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20240418_1034'),
        ('users', '0019_customuser_is_approved'),
    ]

    operations = [
    ]
