# Generated by Django 3.2.13 on 2024-04-25 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_merge_20240418_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Временное хранилище пользователей',
                'verbose_name_plural': 'Хранилище',
            },
        ),
    ]
