# Generated by Django 3.2.13 on 2024-04-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_temporaryuserdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryuserdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='temporaryuserdata',
            name='token',
        ),
    ]
