# Generated by Django 3.2.13 on 2023-11-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Звездочки пользователя',
                'verbose_name_plural': 'Звездочки пользователя',
            },
        ),
    ]
