# Generated by Django 3.2.13 on 2024-04-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_auto_20240411_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='count',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
    ]
