# Generated by Django 3.2.13 on 2024-04-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0003_alter_star_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='username',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='Кому отзыв'),
        ),
    ]
