# Generated by Django 3.2.13 on 2024-04-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0004_star_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='author',
            field=models.CharField(max_length=15, unique=True, verbose_name='Кто оставил отзыв'),
        ),
        migrations.AlterField(
            model_name='star',
            name='username',
            field=models.CharField(max_length=15, unique=True, verbose_name='Кому отзыв'),
        ),
    ]
