# Generated by Django 3.2.13 on 2024-04-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0005_auto_20240411_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='author',
            field=models.CharField(max_length=15, verbose_name='Кто оставил отзыв'),
        ),
        migrations.AlterField(
            model_name='star',
            name='username',
            field=models.CharField(max_length=15, verbose_name='Кому отзыв'),
        ),
    ]
