# Generated by Django 3.2.13 on 2023-11-02 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0002_auto_20231102_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_comment', models.TextField(max_length=1000, verbose_name='Комментарий отклика')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ad', verbose_name='Объявление')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Откликнувшийся')),
            ],
            options={
                'verbose_name': 'Откликнувшийся',
                'verbose_name_plural': 'Откликнувшиеся',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='responders',
            field=models.ManyToManyField(related_name='ads_responded', through='ads.AdResponse', to=settings.AUTH_USER_MODEL, verbose_name='Откликнувшиеся'),
        ),
    ]
