# Generated by Django 3.2.13 on 2023-11-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20231116_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
