# Generated by Django 3.2.13 on 2024-03-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_adresponse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='media/files', verbose_name='Файлы'),
        ),
    ]
