# Generated by Django 3.2.13 on 2024-03-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_ad_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adfile',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='files',
        ),
        migrations.AddField(
            model_name='ad',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='ads', to='ads.AdFile', verbose_name='Файлы'),
        ),
    ]
