# Generated by Django 3.2.13 on 2024-03-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20240314_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
