# Generated by Django 3.2.13 on 2024-03-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_auto_20240314_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вид'),
        ),
    ]
