# Generated by Django 3.2.13 on 2024-09-19 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_ad_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adfile',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ads.ad', verbose_name='Объявление'),
            preserve_default=False,
        ),
    ]
