from django.urls import path
from .views import (
    AdListCreateView,
    AdDetailView,
    AdFileUploadView,
    AdFileListView,
    AdFileDeleteView,
    AdResponseView,
    AdExecutorView,
    UserAdsView,
    UserClosedAdsView,
    AdsInProgressView,
    CloseAdView,
    # DeleteAdView,
    GetResponsesView,
    TypeChangeView,
    CreateTypesView,
    CreateCategoriesView,
    CategoryChangeView,
    MyWorkListView,
    CustomerArchiveView,
    ExecutorArchiveView,
)

urlpatterns = [
    path('ads/', AdListCreateView.as_view(), name='ad-list'),
    path('ads/<int:pk>/', AdDetailView.as_view(), name='ad-detail'),
    path('ads/files/upload/', AdFileUploadView.as_view(), name='ad-file-upload'),
    path('ads/files/', AdFileListView.as_view(), name='ad-file-list'),
    path('ads/files/delete/', AdFileDeleteView.as_view(), name='ad-file-delete'),
    path('ads/response/', AdResponseView.as_view(), name='ad-response'),
    path('ads/executor/', AdExecutorView.as_view(), name='ad-executor'),
    path('users/ads/', UserAdsView.as_view(), name='user-ads'),
    path('users/ads/closed/', UserClosedAdsView.as_view(), name='user-closed-ads'),
    path('users/ads/in-progress/', AdsInProgressView.as_view(), name='ads-in-progress'),
    path('ads/close/', CloseAdView.as_view(), name='close-ad'),
    # path('ads/delete/', DeleteAdView.as_view(), name='delete-ad'),
    path('ads/responses/', GetResponsesView.as_view(), name='get-responses'),
    path('types_create/', CreateTypesView.as_view(), name='types-create'),
    path('types_change/', TypeChangeView.as_view(), name='types-change'),
    path('categories_create/', CreateCategoriesView.as_view(), name='categories-create'),
    path('categories_change/', CategoryChangeView.as_view(), name='categories-change'),
    path('my_work/', MyWorkListView.as_view(), name='my_work'),
    path('archive/customer/', CustomerArchiveView.as_view(), name='customer-archive'),
    path('archive/executor/', ExecutorArchiveView.as_view(), name='executor-archive'),
]
