# Generated by Django 3.2.13 on 2024-04-18 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='created_by',
            new_name='author',
        ),
    ]
