# Generated by Django 3.2.13 on 2024-04-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_created_by_discussion_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='status',
            field=models.CharField(choices=[('closed', 'Закрытое'), ('in_progress', 'Обсуждается')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
    ]
